(source gnu)
(source marmalade)
(source melpa)

(depends-on "apache-mode")
(depends-on "auto-complete")
(depends-on "exec-path-from-shell")
(depends-on "flycheck")
(depends-on "init-loader")
(depends-on "js2-mode")
(depends-on "markdown-mode")
(depends-on "pallet")
(depends-on "redo+")
(depends-on "ruby-block")
(depends-on "scss-mode")
(depends-on "ssh-config-mode")
(depends-on "yaml-mode")
(depends-on "yasnippet")
