(source gnu)
(source marmalade)
(source melpa)

(depends-on "apache-mode")
(depends-on "apropospriate-theme")
(depends-on "auto-complete")
(depends-on "exec-path-from-shell")
(depends-on "flycheck")
(depends-on "init-loader")
(depends-on "js2-mode")
(depends-on "json-mode")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "pallet")
(depends-on "redo+")
(depends-on "ruby-block")
(depends-on "ruby-end")
(depends-on "scss-mode")
(depends-on "smart-newline")
(depends-on "ssh-config-mode")
(depends-on "sublime-themes")
(depends-on "yaml-mode")
(depends-on "yasnippet")
(depends-on "zenburn-theme")

(depends-on "railscasts-theme" :git "https://github.com/noriaki/railscasts-theme.git")
